//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magazynEntities : DbContext
    {
        public magazynEntities()
            : base("name=magazynEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artykul> Artykuly { get; set; }
        public virtual DbSet<Artykul_w_transakcji> Artykuly_w_transakcji { get; set; }
        public virtual DbSet<Dostawca> Dostawcy { get; set; }
        public virtual DbSet<Kategoria> Kategorie { get; set; }
        public virtual DbSet<Klient> Klienci { get; set; }
        public virtual DbSet<Adres> Ksiazka_adresow { get; set; }
        public virtual DbSet<Pracownik> Pracownicy { get; set; }
        public virtual DbSet<Transakcja> Transakcje { get; set; }
    }
}
